### ISSUE TITLE
CDI Ambiguous dependencies for injecting SqlSession

### ISSUE THREAD

**Issue by HaVonTe** [mybatis/cdi#1]
It's not possible to create an own @Producer Method for an SqlSession with mybatis-cdi. When I deploy such a bean, it throws Ambiguous dependencies Exceptions because glassfish thinks MyBatisBean is producing the same SqlSession as my own Bean.

**Comment by mnesarco** [comment]
I can add a @MapperSession annotation, so if you want to inject SqlSessions you must annotate the injection point, but mybatis-cdi will not use your custom SqlSession producers, it relies in SqlSessionFactory producers only. So if you create SqlSession producers, you are responsible for its lifecycle management and transactionality, and injected Mappers will not be bounded to your custom sessions.

**Comment by mnesarco** [comment]
fixed in beta5: fd05599683d01af4bcde31a45511ff4649e50963

**Comment by mnesarco** [comment]
@HaVonTe  beta5 introduced important changes: http://www.mybatis.org/cdi/changes.html
from beta5 you can inject unmanaged SqlSession directly.
