### ISSUE TITLE
Unsatisfied dependencies with Tomcat and Weld

### ISSUE THREAD

**Issue by raupachz** [mybatis/cdi#10]
Hi,

we are running Tomcat 8 with Weld 2.2.8. Dependency Injection works and our code runs fine.

```
@ApplicationScoped
public class SqlSessionFactoryProducer {
    
    @Produces @ApplicationScoped
    public SqlSessionFactory produce() {
        try {
            String resource = "de/grasmueck/data/Configuration.xml";
            InputStream inputStream = Resources.getResourceAsStream(resource);
            SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
            return sqlSessionFactory;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
```

All our DAO Classes share the same basic structure.

```
@RequestScoped
public class MyExamplePojoDAO {
    
    @Inject
    private SqlSessionFactory sqlSessionFactory;

    public List<MyExamplePojo> select() {
        try (SqlSession session = sqlSessionFactory.openSession()) {
            MyExamplePojoMapper mapper = session.getMapper(MyExamplePojoMapper.class);
            return mapper.select();
        }
    }
}
```

I am trying to get rid of the boilerplate code with Mybatis-CDI and inject with `@Mapper`. During deployment I end up with the following exception.

```
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type UserTransaction with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private transient org.mybatis.cdi.JtaTransactionInterceptor.userTransaction
  at org.mybatis.cdi.JtaTransactionInterceptor.userTransaction(JtaTransactionInterceptor.java:0)
```

Makes sense because with don't work with JTA Transaction at all. Any chance to make this work? We don't want to work with a full blown application server right now.

**Edit** 
I forgot our Configuration.xml. It is rather simple. We have a single environment with a JDBC Transaction Manager and a POOLED datasource.

**Comment by rickcr** [comment]
Having the same issue trying to deploy to Tomcat 7. 

(note when trying to deploy to jboss 6.. I end up with  java.lang.ClassCastException: org.jboss.weld.bootstrap.WeldBootstrap cannot be cast to org.jboss.weld.bootstrap.api.CDI11Bootstrap)

Oh I how I wish someone would make a simple war application showing how to glue all this together. I'm working on such an example, but it's been a nightmare so far. Does anyone know of a link to such an application? (The only one I found is to one that builds things as an ear, but I haven't gotten that to run correctly either on jboss.) /frustrated

**Comment by gallegote** [comment]
Hi

I have the same problem with deploying to Tomcat 7.

Since I do not use JTA Transaction in my application. I've solved by deleting the JtaTransactionInterceptor class that is inside the mybatis-cdi-1.0.0-beta1.jar file.

**Comment by hazendaz** [comment]
Better option is to add javax.transaction to your tomcat or locally, either will work.

User this one so you still have java 6 support since this is on weld 2.1.2

    <dependency>
      <groupId>javax.transaction</groupId>
      <artifactId>transaction-api</artifactId>
      <version>1.1</version>
    </dependency>

In the meantime, I'm going to do a PR to fix this in the build by making this a compile scoped requirement but optional given CDI supports servlet containers that don't have this library by default.

**Comment by raupachz** [comment]
Unfortunately that does not seem to work with Weld 2.2.11. I added the `transaction-api` to my pom.xml.

**Comment by hazendaz** [comment]
Try version 1.2 of the api.  Weld 2.2 requires that level.  If you are using java 6 still you can use jboss version.

--- Original Message ---

**Comment by raupachz** [comment]
@hazendaz I don't find 1.2 of transaction-api in Maven Central.

**Comment by raupachz** [comment]
Ok, I tried with
```
<dependency>  
            <groupId>javax.transaction</groupId>  
            <artifactId>javax.transaction-api</artifactId>  
            <version>1.2</version>             
        </dependency>
```
Same error message.

**Comment by hazendaz** [comment]
I think I understand the issue better at this point.  There is no transaction implementation so weld is tripped up on the injection of an interface.  I'll do some digging to see what best solution is outside of adding more jars...

--- Original Message ---

**Comment by hazendaz** [comment]
There is a fix mybatis needs.  Rather than simple inject it needs to use instance and then instance.get so that it essentially becomes optional.  I'll look at getting that in place tonight.  In the meantime the solution would be to delete that class out of the jar.  I'll get you a new jar to test tomorrow.  Provided your test pans out I'll see about getting this fast tracked for a release.

--- Original Message ---

**Comment by raupachz** [comment]
No hurry. I can try it out tomorrow. Glad to help you out.

**Comment by hazendaz** [comment]
I have a test project I use as sort of a catch all.  In that I had deltaspike in use for testing CDI.  I replicated your issue simply by adding mybatis-cdi and running my test class.  I'm merging the code to the code base as test cases work with the fix.  I don't have access at the moment to do a direct release so I'm making this available for you at this location.  I did this as if it is the actual release in case you prevent snapshot usage.  Please give this a go and let me know if it solves your issues.

https://github.com/hazendaz/distro-folder

**Comment by raupachz** [comment]
We are getting somewhere. I tried the jar you provided. The `DeploymentException` is gone. Unfortunately I end you with a different exception. The problem could be on my end however. Not sure.

```
Caused by: org.mybatis.cdi.MybatisCdiConfigurationException: There are no SqlSessionFactory producers properly configured.
	at org.mybatis.cdi.CDIUtils.findSqlSessionFactory(CDIUtils.java:54)
	at org.mybatis.cdi.SerializableMapperProxy.getMapper(SerializableMapperProxy.java:55)
	at org.mybatis.cdi.SerializableMapperProxy.<init>(SerializableMapperProxy.java:47)
	at org.mybatis.cdi.MyBatisBean.create(MyBatisBean.java:107)
```

Here is my `SqlSessionFactoryProducer` class that used to work but is not found anymore.

```
@Produces @ApplicationScoped
    public SqlSessionFactory produce() {
        try {
            String resource = "org/acme/data/Configuration.xml";
            InputStream inputStream = Resources.getResourceAsStream(resource);
            SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
            return sqlSessionFactory;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by christianpoitras** [comment]
This looks a lot like #11.

**Comment by raupachz** [comment]
Yes, It does. Adding `@ApplicationScoped` to the class `SqlSessionFactoryProvider` did not help. So the two are related somehow. Anything I can do to help out? I am not so familiar with the intrinsics of CDI but I have time and a project to try things out.

**Comment by hazendaz** [comment]
Can you drop weld back to 2.1.2 to see if that works in tomcat?

--- Original Message ---

**Comment by raupachz** [comment]
Works like a charm!

```
<dependency>
    <groupId>org.jboss.weld.servlet</groupId>
    <artifactId>weld-servlet</artifactId>
    <version>2.1.2.Final</version>
</dependency>
<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-cdi</artifactId>
    <version>1.0.0-beta2</version>
</dependency>
```

**Comment by hazendaz** [comment]
Cool.  We have a base working on tomcat!  I don't have access to code right now but will give this a look tonight to get to 2.2.  Are there any other logs on 2.2 that might help isolate issue?

--- Original Message ---

**Comment by raupachz** [comment]
Ist just boils down to the `MybatisCdiConfigurationException ` mentioned above, but I do some checking. I let you know if I find anything else.

**Comment by hazendaz** [comment]
I have this working under tomcat without any issues.  My beans.xml is formatted for 2.2.x so maybe that makes a difference.  My mappers load up just fine.  I have three separate sql session factories as well.  All named and all working as one would expect.  I wasn't physically using mybatis-cdi until this issue was raised so now I am.  Maybe you can more information about your tomcat setup as well as all the dependencies that end up in your WAR.

I'm using weld 2.2.11.

**Comment by raupachz** [comment]
Thanks! That is interesting to know. Let me create a mcve and find the culprit. My stack is rather simple: JSF 2.2, Omnifaces and MyBatis. If I find something I open a new issue.

**Comment by hazendaz** [comment]
Things get a little tricky after Weld 2.2.5.  Annotations start to explicitly matter more.  I've had to hund down lots of similar issues so that might be what is causing you issues.  I've been running this now for a few days and it works like a champ.  Let me know if you have any luck on this.  I'm using all those same things you mention plus some.  The beta2 version has now been released out to central as well.

**Comment by raupachz** [comment]
Jeremy is the version in Maven central the same you send me a week ago? Yesterday I was creating a simple JSF 2.2 project with Weld 2.2.11 and it worked like you said. No problems at all.

So I guess this project I am working on has some other issue. Have to figure that out. What do you mean by formatted for 2.2.x? I still use this `beans.xml`:

```
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
       bean-discovery-mode="annotated">
</beans>
```

**Comment by hazendaz** [comment]
There were so many breaking changes with 2.2 that I think I confused myself on the introduction of beans xml changes.  I believe you are good there.  That actually came with 2.x.  sorry for the confusion.

--- Original Message ---
