### ISSUE TITLE
Unable to use MyBatis-CDI with GlassFish 4 and 4.1

### ISSUE THREAD

**Issue by pholding** [mybatis/cdi#11]
I'm unable to get MyBatis-CDI working with GlassFish 4 and GlassFish 4.1 due to a `MybatisCdiConfigurationException` exception being thrown with the description "There are no SqlSessionFactory producers properly configured."

The code for the SqlSessionFactory I'm using is as follow:

```
import javax.annotation.Resource;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;
import javax.sql.DataSource;

import org.apache.ibatis.mapping.Environment;
import org.apache.ibatis.session.Configuration;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.apache.ibatis.transaction.TransactionFactory;
import org.apache.ibatis.transaction.jdbc.JdbcTransactionFactory;

public class SqlSessionFactoryProvider {

    @Resource (lookup="jdbc/MyDatabase")
    DataSource dataSource;

    @Produces
    @ApplicationScoped
    public SqlSessionFactory produceFactory() {
        TransactionFactory transactionFactory = new JdbcTransactionFactory();
        Environment environment = new Environment("development",
            transactionFactory, dataSource);
        Configuration configuration = new Configuration(environment);
        configuration.addMapper(ToDoItemMapper.class);
        SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder()
            .build(configuration);
        return sqlSessionFactory;
    }
}
```

I've stepped through the code of the MyBatis-CDI module and have found that when the follow line of code in `CDIUtils findSqlSessionFactory(...)` is executed it fails find any beans that return `SqlSessionFactory.class`.

`beans = beanManager.getBeans(SqlSessionFactory.class, qualifiers.toArray(new Annotation[]{}));`

I've tried running my program on GlassFish 4 and 4.1 and they both have the same problem, but it works fine if I run my program on WildFly 8.1. My first thought was that it might be a problem with the version of Weld shipped with Glassfish but it turns out that GlassFish 4.1 is running Weld version 2.2.2 whereas WildFly is running Weld version 2.1.2.

Is there anything I can do in GlassFish, my code or in the MyBatis-CDI module to overcome this problem when running in GlassFish?

**Comment by christianpoitras** [comment]
Try adding @ApplicationScoped to your SqlSessionFactoryProvider.

**Comment by pholding** [comment]
I've just tried adding `@ApplicationScoped` to the `SqlSessionFactoryProvider` class but I'm still getting a `MybatisCdiConfigurationException` thrown with the description "There are no SqlSessionFactory producers properly configured."

**Comment by christianpoitras** [comment]
I guess it will be difficult to find the reason why Weld behaves differently in 2.2.2 compared to 2.1.2.

My only other suggestion would be to force the declaration of the bean in beans.xml and see if that helps.
You could also try to add the Default and/or Any annotation to qualifiers.
<code>
beans = beanManager.getBeans(SqlSessionFactory.class, new AnnotationLiteral<Default>() {});
</code>

**Comment by pholding** [comment]
I've tried adding `@Default` and `@Any` to the method but the problem still remains.

I've also found out that there seems to be a GlassFish specific release of Weld, although I don't know what is different between the standard release and the GlassFish release, and there doesn't appear to be a GlassFish specific release of Weld 2.1.2 in Maven Central. I tried downloading the GlassFish release of Weld 2.2.10.SP1 from Maven Central (https://repo1.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/) but that didn't fix the problem either.

Any idea how I would force the declaration of SqlSessionFactoryProvider in beans.xml? I've taken a look on Google but the only examples I can find are for declaring interceptors and decorators.

**Comment by christianpoitras** [comment]
Normally, using
<code>
beans = beanManager.getBeans(SqlSessionFactory.class, new AnnotationLiteral<Any>() {}); 
</code>
CDI should return all SqlSessionFactory beans. To test this, you will need to create your own copy of mybatis-cdi.

After checking, it is not possible to force the declaration of a bean in beans.xml. You can only force the use of alternatives. I am not a CDI expert, sorry.

**Comment by pholding** [comment]
I've copied the various classes that make up mybatis-cdi directly into my program and have registered the extension in `META-INF/services/javax.enterprise.inject.spi.Extension`, and I can now successfully inject mappers into my program and run queries using MyBatis.

Given that this works in Weld without any changes and also in GlassFish when I copy the mybatis-cdi classes into my program, I'm wondering whether this is either a bug in GlassFish itself or the GlassFish specific release of Weld.

**Comment by christianpoitras** [comment]
Thanks. That's an interesting bit of information. I'll have a look into it and see if there is anything to do to solve the issue.

**Comment by hazendaz** [comment]
Just a few ideas...

Could this have something to do with beans.xml not being setup for 2.2.x?  While it is not required in glassfish 4.1, if I recall correctly, what it does changed.  Annotations are default now.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
         http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
    version="1.1" bean-discovery-mode="annotated">
</beans>

Other possible issue is the fact that newer CDI no longer just injects things for sake of injection.  It requires a scope regardless.  @Dependent is the scope that should be set on anything that is performing injection if no scope is to be listed meaning it is going to be part of some other scope.  So lets us say the piece you didn't show where you are @inject on the producer you have, does that class have a scope itself?

**Comment by fgianneschi** [comment]
I'm running WildFly 8.2.1 and I've the same problem. Any updates?

**Comment by sjljsw** [comment]
hello ,I run glassfish 4.1 or payrar, the same and you have the same problem. You do not know the problem has been solved? I am very anxious to solve this problem.My weld-osgi-bundle upgrade to 2.3.2.final. Can not solve the problem.

I suspect that 
beans = beanManager.getBeans(SqlSessionFactory.class, qualifiers.toArray(new Annotation[]{}));.
Can not find an instance

**Comment by quarkalone** [comment]
Hello,
I'm having a difficult time with glassfish 4.1.  Does anyone have a working example?  Currently, when I try to inject a mapper I get this message in the log:

Severe:   Error Rendering View[/index.xhtml]
org.mybatis.cdi.MybatisCdiConfigurationException: There are no SqlSessionFactory producers properly configured.

However, some lines before I get:
Info:   MyBatis CDI Module - Activated
Info:   MyBatis CDI Module - Mapper dependency discovered: org.jayasoft.mapper.PersonaMapper

Regards.

**Comment by mnesarco** [comment]
Hi, I have tested the beta5 against Payara 4.1 (Glassfish 4.1) and TomEE-Plus 7.0.1.
The test code can be found here: https://github.com/mnesarco/mybatis-cdi-samples
