### ISSUE TITLE
UnsatisfiedResolutionException: Api type [] is not found with the qualifiers...

### ISSUE THREAD

**Issue by zory** [mybatis/cdi#114]
Hi. I'm struggling with MyBatis-CDI injection to other bean. Maybe you have some ideas what I'm doing wrong and what did I miss?
Error I have in my test project:
```
17-Mar-2019 22:24:29.639 SEVERE [http-nio-8080-exec-4] org.apache.openejb.cdi.OpenEJBLifecycle.startApplication CDI Beans module deployment failed
 org.apache.webbeans.exception.WebBeansDeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Api type [com.mybatis.dao.ServersMapper] is not found with the qualifiers 
Qualifiers: [@javax.enterprise.inject.Default()]
for injection into Field Injection Point, field name :  serversMapper, Bean Owner : [ThirdComp, WebBeansType:MANAGED, Name:thirdComp, API Types:[com.mybatis.ThirdComp,java.lang.Object], Qualifiers:[javax.enterprise.inject.Default,javax.enterprise.inject.Any]]
	at org.apache.webbeans.config.BeansDeployer.deploy(BeansDeployer.java:327)
...
```
My setup - I'm using mybatis generator to generate my Models, DAO classes and mappers xml's. As my generator works, i assume that there is no problems in that code. Then mybatis and mybatis-cdi configuration:
Maven:
```
        <dependency>
            <groupId>org.mybatis.generator</groupId>
            <artifactId>mybatis-generator-maven-plugin</artifactId>
            <version>1.3.7</version>
        </dependency>

        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.4.2</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-cdi</artifactId>
            <version>1.0.0-beta7</version>
        </dependency>
```
MyBatisConfig:
```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration
        PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>
    <typeAliases>
        <typeAlias type="com.mybatis.model.Servers" alias="Servers"/>
    </typeAliases>
    <environments default="development">
        <environment id="development">
            <transactionManager type="MANAGED"/>
            <dataSource type="JNDI">
                <property name="data_source" value="openejb:Resource/ServersDataSource"/>
            </dataSource>
        </environment>
    </environments>
    <mappers>
        <mapper resource="mybatis/xml/ServersMapper.xml"/>
    </mappers>
</configuration>
```
I added @Mapper annotation to my ServersMapper.java file (everything else is unchanged from generation)
Then I have 
```
@ApplicationScoped
public class MyBatisDemoResources {

    @Produces
    @ApplicationScoped
    @SessionFactoryProvider
    private SqlSessionFactory produceSqlSessionFactory() {
        try {
            return new SqlSessionFactoryBuilder().build(
                    Resources.getResourceAsStream("MyBatisConfig.xml")
            );
        } catch (IOException e) {
            throw new RuntimeException("MyBatisResources.produceSqlSessionFactory(): ", e);
        }
    }
}
```
And finally my call from other java class:
```
@Model
public class SomeClass {
    @Inject
    private ServersMapper serversMapper;
...Other code...
```
Thanks in advance, hope information I provided is enough to see something : )

**Comment by hazendaz** [comment]
Can you try the latest release of the cdi model?  I'm pretty sure the beta used here had issues.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zory** [comment]
Thank You for response.
I tried with 1.0.0 version before, but result was the same, so I updated to beta version.

**Comment by mnesarco** [comment]
Latest version is 1.1.0. Please try with latest version.

**Comment by zory** [comment]
Tried with some different versions (newest included). Result is the same.
Interesting think though: found a public project with similar setup of mine, stripped everything except mybatis/cdi and everything woks fine in there, but couldn't find a meaningful difference between the two projects. Project I found would trigger the same error if mybatis version changed to older/newer, but works fine with initial versions. But my project does not work with either.
Because of that, my closest guess is, that I need specific versions of specific dependencies.
Tried to play with different versions of mybatisgenerator, mybatis, mybatiscdi, hybernate and jBoss-cdi so far.
Maybe there are additional dependencies needed to work with mybatis/mybatis-cdi? 
Will keep you posted.

**Comment by hazendaz** [comment]
@zory Try using @Any servers mapper and see if that helps at all.

**Comment by mnesarco** [comment]
@zory, can you provide a minimal sample project to reproduce the problem?

**Comment by hazendaz** [comment]
I'm going to close this one as it sounds like a setup issue.  This looks pretty close to our test setup.
