### ISSUE TITLE
Ready for GA Release

### ISSUE THREAD

**Issue by mnesarco** [mybatis/cdi#59]
Hi @hazendaz , I think we are ready for our first General Availability Release.

- All passivation/serialization issues were resolved.
- Docs are up to date
- Tested with major Containers:
   * Payara 4.1 (Glassfish 4.1)
   * TomEE 7.0.1 Plus
   * Wildfly 10.1.0
   * WAS Liberty with Java EE 7 Full Platform 16.0.0.4
   * Oracle WebLogic 12c
- There are no more open issues.
- Clarification about not supporting  cdi 1.0 is in the README.

**Comment by hazendaz** [comment]
Sounds good.  Do you want to add a link to your sample cdi project?

**Comment by mnesarco** [comment]
Hi @hazendaz , I have added the link to samples in the Readme.

**Comment by hazendaz** [comment]
I was looking at sonatype statistics.  Pretty healthy usage of this.  At the moment 70% is on beta 2 for past month at around 700+ downloads.  Second is beta 6 around 100+ downloads.  Maybe give it to Saturday to see if anyone else on the team wants to comment.  If we don't hear anything I say we pull the trigger.

**Comment by hazendaz** [comment]
Released.
